import type { Metadata } from "next";
import { Spectral } from "next/font/google";
import { Footer } from "@/app/_components/Footer/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spectralFont = Spectral({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={spectralFont.className}>
      <body>
        {children}

        <Footer />
      </body>
    </html>
  );
}
