import type { Metadata } from "next";
import { Spectral } from "next/font/google";
import { Footer } from "@/app/_components/Footer/Footer";
import { Header } from "@/app/_components/Header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Blog de Antoine Raymond | Articles",
  description: "Generated by create next app",
};

const spectralFont = Spectral({
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={spectralFont.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
